# Generated by Django 4.2.1 on 2023-06-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('xotira', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memory', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('describtion', models.TextField()),
                ('brand', models.CharField(max_length=50)),
                ('price', models.PositiveSmallIntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'model',
            },
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Telefon',
            },
        ),
    ]
