# Generated by Django 4.2.1 on 2023-06-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='xotira',
        ),
        migrations.AddField(
            model_name='brand',
            name='phones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.telefon'),
        ),
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.brand'),
        ),
    ]
