# Generated by Django 4.2.1 on 2023-06-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_brand_xotira_brand_phones_product_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='describtion',
        ),
    ]
