# Generated by Django 4.2.1 on 2023-06-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
